### ISSUE TITLE
queryForSlaves() does not filter out the unavailable slaves

### ISSUE THREAD

**Issue by yudecheng** [FZambia/go-sentinel#2]
If one of the slaves stops, the query results of command “SENTINEL slaves master_name“ will also contain the stopped slave. We can filter out these unavailable slaves according to the “flags” field.
The “flags” of the unavailable slave contains "disconnected" or "s_down".
![s1](https://user-images.githubusercontent.com/25314582/28451640-fe678e8e-6e20-11e7-8b0d-f0ee93f58212.jpeg)
![s2](https://user-images.githubusercontent.com/25314582/28451641-02383158-6e21-11e7-80db-94f2823397b9.jpeg)

**Comment by yudecheng** [comment]
![s1](https://user-images.githubusercontent.com/25314582/28451561-7f1bab38-6e20-11e7-9456-e9981cfea75b.jpeg)

**Comment by yudecheng** [comment]
I am sorry that close this issue by mistake.

**Comment by FZambia** [comment]
@yudecheng thanks for your report and suggested fix, I'll come up with backwards compatible pull request very soon.

**Comment by FZambia** [comment]
@yudecheng please look at #3 - is it ok? I think it's pretty reasonable approach which we can extend in future.

**Comment by yudecheng** [comment]
Busy with work recently, has not replied for you in time, I am sorry.I read
this modification just now

2017-08-04 21:01 GMT+08:00 Alexandr Emelin <notifications@github.com>:

**Comment by yudecheng** [comment]
Busy with work recently, has not replied for you in time, I am sorry. I
read this modification just now. I think it is very elegant. Thank you very
much.

2017-08-06 12:51 GMT+08:00 余德成 <yudechengscut@gmail.com>:
